config/routes.rb
Phonetic::Application.routes.draw do
  get "home/index"
  post "home/translate"

  root 'home#index'

end

app/models/translator.rb
class Translator
  def translate(text)
    result = text.clone

    words(text).each do |word|
      if word.present?
        result[word] = get_replace(word)
      end
    end
    result
  end

  def words(text)
    text.split(/[^\w\-\.\'']/)
  end

  def get_replace(word)
    start = word.match(/^[\'\"]/)
    finish = word.match(/[\.\,\;\'\"]$/)
    temp = word

    if start
      temp = temp[1,-1]
    end

    if finish
      temp = temp[0,-2]
    end

    new_text = Word.where(:text => word.upcase).first
    word = new_text ? new_text.phonetic : word

    if start
      word = "#{start}#{word}"
    end

    if finish
      word = "#{word}#{finish}"
    end

    word
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  def self.new_word(word, word_phonetics)
    record = Word.new
    record.text = word
    arr = Array.new
    word_phonetics.each do |p|
      arr << to_phonetic(p)
    end
    record.phonetic = arr.join
    record.save
  end

  private
  def self.to_phonetic(p)
    if is_phonetic p
      return PHONETICS[p]
    end

    stress = p.last.match(/\d$/)
    if stress
      d = p[0..-2]
      if is_phonetic d
        data = "#{PHONETICS[d]}"
        return data
      end
    end

    ''
  end

  def self.is_phonetic(text)
    PHONETICS.keys.include?(text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def translate
    if params[:text]
      @text = params[:text]
      @phonetic_text = Translator.new.translate(params[:text])
    end
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
= form_tag home_translate_path, :method => :post
  textarea#text style='width:900px;height:200px' name='text'
  input type='submit' value="Submit"


- if @phonetic_text
  = @text
  br/
  = @phonetic_text

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Phonetic"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-fluid-top

    .container-fluid

      .row-fluid

        .span9
          = bootstrap_flash
          = yield

      footer